class Countries {
  static List<Map<String, String>> get list => _list;
  static final List<Map<String, String>> _list = [
    {"name": "Afghanistan", "dial": "+93", "alpha2": "AF"},
    {"name": "Aland Islands", "dial": "+358", "alpha2": "AX"},
    {"name": "Albania", "dial": "+355", "alpha2": "AL"},
    {"name": "Algeria", "dial": "+213", "alpha2": "DZ"},
    {"name": "AmericanSamoa", "dial": "+1684", "alpha2": "AS"},
    {"name": "Andorra", "dial": "+376", "alpha2": "AD"},
    {"name": "Angola", "dial": "+244", "alpha2": "AO"},
    {"name": "Anguilla", "dial": "+1264", "alpha2": "AI"},
    {"name": "Antarctica", "dial": "+672", "alpha2": "AQ"},
    {"name": "Antigua and Barbuda", "dial": "+1268", "alpha2": "AG"},
    {"name": "Argentina", "dial": "+54", "alpha2": "AR"},
    {"name": "Armenia", "dial": "+374", "alpha2": "AM"},
    {"name": "Aruba", "dial": "+297", "alpha2": "AW"},
    {"name": "Australia", "dial": "+61", "alpha2": "AU"},
    {"name": "Austria", "dial": "+43", "alpha2": "AT"},
    {"name": "Azerbaijan", "dial": "+994", "alpha2": "AZ"},
    {"name": "Bahamas", "dial": "+1242", "alpha2": "BS"},
    {"name": "Bahrain", "dial": "+973", "alpha2": "BH"},
    {"name": "Bangladesh", "dial": "+880", "alpha2": "BD"},
    {"name": "Barbados", "dial": "+1246", "alpha2": "BB"},
    {"name": "Belarus", "dial": "+375", "alpha2": "BY"},
    {"name": "Belgium", "dial": "+32", "alpha2": "BE"},
    {"name": "Belize", "dial": "+501", "alpha2": "BZ"},
    {"name": "Benin", "dial": "+229", "alpha2": "BJ"},
    {"name": "Bermuda", "dial": "+1441", "alpha2": "BM"},
    {"name": "Bhutan", "dial": "+975", "alpha2": "BT"},
    {
      "name": "Bolivia, Plurinational State of",
      "dial": "+591",
      "alpha2": "BO"
    },
    {"name": "Bosnia and Herzegovina", "dial": "+387", "alpha2": "BA"},
    {"name": "Botswana", "dial": "+267", "alpha2": "BW"},
    {"name": "Brazil", "dial": "+55", "alpha2": "BR"},
    {
      "name": "British Indian Ocean Territory",
      "dial": "+246",
      "alpha2": "IO"
    },
    {"name": "Brunei Darussalam", "dial": "+673", "alpha2": "BN"},
    {"name": "Bulgaria", "dial": "+359", "alpha2": "BG"},
    {"name": "Burkina Faso", "dial": "+226", "alpha2": "BF"},
    {"name": "Burundi", "dial": "+257", "alpha2": "BI"},
    {"name": "Cambodia", "dial": "+855", "alpha2": "KH"},
    {"name": "Cameroon", "dial": "+237", "alpha2": "CM"},
    {"name": "Canada", "dial": "+1", "alpha2": "CA"},
    {"name": "Cape Verde", "dial": "+238", "alpha2": "CV"},
    {"name": "Cayman Islands", "dial": "+ 345", "alpha2": "KY"},
    {"name": "Central African Republic", "dial": "+236", "alpha2": "CF"},
    {"name": "Chad", "dial": "+235", "alpha2": "TD"},
    {"name": "Chile", "dial": "+56", "alpha2": "CL"},
    {"name": "China", "dial": "+86", "alpha2": "CN"},
    {"name": "Christmas Island", "dial": "+61", "alpha2": "CX"},
    {"name": "Cocos (Keeling) Islands", "dial": "+61", "alpha2": "CC"},
    {"name": "Colombia", "dial": "+57", "alpha2": "CO"},
    {"name": "Comoros", "dial": "+269", "alpha2": "KM"},
    {"name": "Congo", "dial": "+242", "alpha2": "CG"},
    {
      "name": "Congo, The Democratic Republic of the Congo",
      "dial": "+243",
      "alpha2": "CD"
    },
    {"name": "Cook Islands", "dial": "+682", "alpha2": "CK"},
    {"name": "Costa Rica", "dial": "+506", "alpha2": "CR"},
    {"name": "Cote d'Ivoire", "dial": "+225", "alpha2": "CI"},
    {"name": "Croatia", "dial": "+385", "alpha2": "HR"},
    {"name": "Cuba", "dial": "+53", "alpha2": "CU"},
    {"name": "Cyprus", "dial": "+357", "alpha2": "CY"},
    {"name": "Czech Republic", "dial": "+420", "alpha2": "CZ"},
    {"name": "Denmark", "dial": "+45", "alpha2": "DK"},
    {"name": "Djibouti", "dial": "+253", "alpha2": "DJ"},
    {"name": "Dominica", "dial": "+1767", "alpha2": "DM"},
    {"name": "Dominican Republic", "dial": "+1849", "alpha2": "DO"},
    {"name": "Ecuador", "dial": "+593", "alpha2": "EC"},
    {"name": "Egypt", "dial": "+20", "alpha2": "EG"},
    {"name": "El Salvador", "dial": "+503", "alpha2": "SV"},
    {"name": "Equatorial Guinea", "dial": "+240", "alpha2": "GQ"},
    {"name": "Eritrea", "dial": "+291", "alpha2": "ER"},
    {"name": "Estonia", "dial": "+372", "alpha2": "EE"},
    {"name": "Ethiopia", "dial": "+251", "alpha2": "ET"},
    {"name": "Falkland Islands (Malvinas)", "dial": "+500", "alpha2": "FK"},
    {"name": "Faroe Islands", "dial": "+298", "alpha2": "FO"},
    {"name": "Fiji", "dial": "+679", "alpha2": "FJ"},
    {"name": "Finland", "dial": "+358", "alpha2": "FI"},
    {"name": "France", "dial": "+33", "alpha2": "FR"},
    {"name": "French Guiana", "dial": "+594", "alpha2": "GF"},
    {"name": "French Polynesia", "dial": "+689", "alpha2": "PF"},
    {"name": "Gabon", "dial": "+241", "alpha2": "GA"},
    {"name": "Gambia", "dial": "+220", "alpha2": "GM"},
    {"name": "Georgia", "dial": "+995", "alpha2": "GE"},
    {"name": "Germany", "dial": "+49", "alpha2": "DE"},
    {"name": "Ghana", "dial": "+233", "alpha2": "GH"},
    {"name": "Gibraltar", "dial": "+350", "alpha2": "GI"},
    {"name": "Greece", "dial": "+30", "alpha2": "GR"},
    {"name": "Greenland", "dial": "+299", "alpha2": "GL"},
    {"name": "Grenada", "dial": "+1473", "alpha2": "GD"},
    {"name": "Guadeloupe", "dial": "+590", "alpha2": "GP"},
    {"name": "Guam", "dial": "+1671", "alpha2": "GU"},
    {"name": "Guatemala", "dial": "+502", "alpha2": "GT"},
    {"name": "Guernsey", "dial": "+44", "alpha2": "GG"},
    {"name": "Guinea", "dial": "+224", "alpha2": "GN"},
    {"name": "Guinea-Bissau", "dial": "+245", "alpha2": "GW"},
    {"name": "Guyana", "dial": "+595", "alpha2": "GY"},
    {"name": "Haiti", "dial": "+509", "alpha2": "HT"},
    {"name": "Holy See (Vatican City State)", "dial": "+379", "alpha2": "VA"},
    {"name": "Honduras", "dial": "+504", "alpha2": "HN"},
    {"name": "Hong Kong", "dial": "+852", "alpha2": "HK"},
    {"name": "Hungary", "dial": "+36", "alpha2": "HU"},
    {"name": "Iceland", "dial": "+354", "alpha2": "IS"},
    {"name": "India", "dial": "+91", "alpha2": "IN"},
    {"name": "Indonesia", "dial": "+62", "alpha2": "ID"},
    {
      "name": "Iran, Islamic Republic of Persian Gulf",
      "dial": "+98",
      "alpha2": "IR"
    },
    {"name": "Iraq", "dial": "+964", "alpha2": "IQ"},
    {"name": "Ireland", "dial": "+353", "alpha2": "IE"},
    {"name": "Isle of Man", "dial": "+44", "alpha2": "IM"},
    {"name": "Israel", "dial": "+972", "alpha2": "IL"},
    {"name": "Italy", "dial": "+39", "alpha2": "IT"},
    {"name": "Jamaica", "dial": "+1876", "alpha2": "JM"},
    {"name": "Japan", "dial": "+81", "alpha2": "JP"},
    {"name": "Jersey", "dial": "+44", "alpha2": "JE"},
    {"name": "Jordan", "dial": "+962", "alpha2": "JO"},
    {"name": "Kazakhstan", "dial": "+77", "alpha2": "KZ"},
    {"name": "Kenya", "dial": "+254", "alpha2": "KE"},
    {"name": "Kiribati", "dial": "+686", "alpha2": "KI"},
    {
      "name": "Korea, Democratic People's Republic of Korea",
      "dial": "+850",
      "alpha2": "KP"
    },
    {"name": "Korea, Republic of South Korea", "dial": "+82", "alpha2": "KR"},
    {"name": "Kuwait", "dial": "+965", "alpha2": "KW"},
    {"name": "Kyrgyzstan", "dial": "+996", "alpha2": "KG"},
    {"name": "Laos", "dial": "+856", "alpha2": "LA"},
    {"name": "Latvia", "dial": "+371", "alpha2": "LV"},
    {"name": "Lebanon", "dial": "+961", "alpha2": "LB"},
    {"name": "Lesotho", "dial": "+266", "alpha2": "LS"},
    {"name": "Liberia", "dial": "+231", "alpha2": "LR"},
    {"name": "Libyan Arab Jamahiriya", "dial": "+218", "alpha2": "LY"},
    {"name": "Liechtenstein", "dial": "+423", "alpha2": "LI"},
    {"name": "Lithuania", "dial": "+370", "alpha2": "LT"},
    {"name": "Luxembourg", "dial": "+352", "alpha2": "LU"},
    {"name": "Macao", "dial": "+853", "alpha2": "MO"},
    {"name": "Macedonia", "dial": "+389", "alpha2": "MK"},
    {"name": "Madagascar", "dial": "+261", "alpha2": "MG"},
    {"name": "Malawi", "dial": "+265", "alpha2": "MW"},
    {"name": "Malaysia", "dial": "+60", "alpha2": "MY"},
    {"name": "Maldives", "dial": "+960", "alpha2": "MV"},
    {"name": "Mali", "dial": "+223", "alpha2": "ML"},
    {"name": "Malta", "dial": "+356", "alpha2": "MT"},
    {"name": "Marshall Islands", "dial": "+692", "alpha2": "MH"},
    {"name": "Martinique", "dial": "+596", "alpha2": "MQ"},
    {"name": "Mauritania", "dial": "+222", "alpha2": "MR"},
    {"name": "Mauritius", "dial": "+230", "alpha2": "MU"},
    {"name": "Mayotte", "dial": "+262", "alpha2": "YT"},
    {"name": "Mexico", "dial": "+52", "alpha2": "MX"},
    {
      "name": "Micronesia, Federated States of Micronesia",
      "dial": "+691",
      "alpha2": "FM"
    },
    {"name": "Moldova", "dial": "+373", "alpha2": "MD"},
    {"name": "Monaco", "dial": "+377", "alpha2": "MC"},
    {"name": "Mongolia", "dial": "+976", "alpha2": "MN"},
    {"name": "Montenegro", "dial": "+382", "alpha2": "ME"},
    {"name": "Montserrat", "dial": "+1664", "alpha2": "MS"},
    {"name": "Morocco", "dial": "+212", "alpha2": "MA"},
    {"name": "Mozambique", "dial": "+258", "alpha2": "MZ"},
    {"name": "Myanmar", "dial": "+95", "alpha2": "MM"},
    {"name": "Namibia", "dial": "+264", "alpha2": "NA"},
    {"name": "Nauru", "dial": "+674", "alpha2": "NR"},
    {"name": "Nepal", "dial": "+977", "alpha2": "NP"},
    {"name": "Netherlands", "dial": "+31", "alpha2": "NL"},
    {"name": "Netherlands Antilles", "dial": "+599", "alpha2": "AN"},
    {"name": "New Caledonia", "dial": "+687", "alpha2": "NC"},
    {"name": "New Zealand", "dial": "+64", "alpha2": "NZ"},
    {"name": "Nicaragua", "dial": "+505", "alpha2": "NI"},
    {"name": "Niger", "dial": "+227", "alpha2": "NE"},
    {"name": "Nigeria", "dial": "+234", "alpha2": "NG"},
    {"name": "Niue", "dial": "+683", "alpha2": "NU"},
    {"name": "Norfolk Island", "dial": "+672", "alpha2": "NF"},
    {"name": "Northern Mariana Islands", "dial": "+1670", "alpha2": "MP"},
    {"name": "Norway", "dial": "+47", "alpha2": "NO"},
    {"name": "Oman", "dial": "+968", "alpha2": "OM"},
    {"name": "Pakistan", "dial": "+92", "alpha2": "PK"},
    {"name": "Palau", "dial": "+680", "alpha2": "PW"},
    {
      "name": "Palestinian Territory, Occupied",
      "dial": "+970",
      "alpha2": "PS"
    },
    {"name": "Panama", "dial": "+507", "alpha2": "PA"},
    {"name": "Papua New Guinea", "dial": "+675", "alpha2": "PG"},
    {"name": "Paraguay", "dial": "+595", "alpha2": "PY"},
    {"name": "Peru", "dial": "+51", "alpha2": "PE"},
    {"name": "Philippines", "dial": "+63", "alpha2": "PH"},
    {"name": "Pitcairn", "dial": "+872", "alpha2": "PN"},
    {"name": "Poland", "dial": "+48", "alpha2": "PL"},
    {"name": "Portugal", "dial": "+351", "alpha2": "PT"},
    {"name": "Puerto Rico", "dial": "+1939", "alpha2": "PR"},
    {"name": "Qatar", "dial": "+974", "alpha2": "QA"},
    {"name": "Romania", "dial": "+40", "alpha2": "RO"},
    {"name": "Russia", "dial": "+7", "alpha2": "RU"},
    {"name": "Rwanda", "dial": "+250", "alpha2": "RW"},
    {"name": "Reunion", "dial": "+262", "alpha2": "RE"},
    {"name": "Saint Barthelemy", "dial": "+590", "alpha2": "BL"},
    {
      "name": "Saint Helena, Ascension and Tristan Da Cunha",
      "dial": "+290",
      "alpha2": "SH"
    },
    {"name": "Saint Kitts and Nevis", "dial": "+1869", "alpha2": "KN"},
    {"name": "Saint Lucia", "dial": "+1758", "alpha2": "LC"},
    {"name": "Saint Martin", "dial": "+590", "alpha2": "MF"},
    {"name": "Saint Pierre and Miquelon", "dial": "+508", "alpha2": "PM"},
    {
      "name": "Saint Vincent and the Grenadines",
      "dial": "+1784",
      "alpha2": "VC"
    },
    {"name": "Samoa", "dial": "+685", "alpha2": "WS"},
    {"name": "San Marino", "dial": "+378", "alpha2": "SM"},
    {"name": "Sao Tome and Principe", "dial": "+239", "alpha2": "ST"},
    {"name": "Saudi Arabia", "dial": "+966", "alpha2": "SA"},
    {"name": "Senegal", "dial": "+221", "alpha2": "SN"},
    {"name": "Serbia", "dial": "+381", "alpha2": "RS"},
    {"name": "Seychelles", "dial": "+248", "alpha2": "SC"},
    {"name": "Sierra Leone", "dial": "+232", "alpha2": "SL"},
    {"name": "Singapore", "dial": "+65", "alpha2": "SG"},
    {"name": "Slovakia", "dial": "+421", "alpha2": "SK"},
    {"name": "Slovenia", "dial": "+386", "alpha2": "SI"},
    {"name": "Solomon Islands", "dial": "+677", "alpha2": "SB"},
    {"name": "Somalia", "dial": "+252", "alpha2": "SO"},
    {"name": "South Africa", "dial": "+27", "alpha2": "ZA"},
    {"name": "South Sudan", "dial": "+211", "alpha2": "SS"},
    {
      "name": "South Georgia and the South Sandwich Islands",
      "dial": "+500",
      "alpha2": "GS"
    },
    {"name": "Spain", "dial": "+34", "alpha2": "ES"},
    {"name": "Sri Lanka", "dial": "+94", "alpha2": "LK"},
    {"name": "Sudan", "dial": "+249", "alpha2": "SD"},
    {"name": "Suriname", "dial": "+597", "alpha2": "SR"},
    {"name": "Svalbard and Jan Mayen", "dial": "+47", "alpha2": "SJ"},
    {"name": "Swaziland", "dial": "+268", "alpha2": "SZ"},
    {"name": "Sweden", "dial": "+46", "alpha2": "SE"},
    {"name": "Switzerland", "dial": "+41", "alpha2": "CH"},
    {"name": "Syrian Arab Republic", "dial": "+963", "alpha2": "SY"},
    {"name": "Taiwan", "dial": "+886", "alpha2": "TW"},
    {"name": "Tajikistan", "dial": "+992", "alpha2": "TJ"},
    {
      "name": "Tanzania, United Republic of Tanzania",
      "dial": "+255",
      "alpha2": "TZ"
    },
    {"name": "Thailand", "dial": "+66", "alpha2": "TH"},
    {"name": "Timor-Leste", "dial": "+670", "alpha2": "TL"},
    {"name": "Togo", "dial": "+228", "alpha2": "TG"},
    {"name": "Tokelau", "dial": "+690", "alpha2": "TK"},
    {"name": "Tonga", "dial": "+676", "alpha2": "TO"},
    {"name": "Trinidad and Tobago", "dial": "+1868", "alpha2": "TT"},
    {"name": "Tunisia", "dial": "+216", "alpha2": "TN"},
    {"name": "Turkey", "dial": "+90", "alpha2": "TR"},
    {"name": "Turkmenistan", "dial": "+993", "alpha2": "TM"},
    {"name": "Turks and Caicos Islands", "dial": "+1649", "alpha2": "TC"},
    {"name": "Tuvalu", "dial": "+688", "alpha2": "TV"},
    {"name": "Uganda", "dial": "+256", "alpha2": "UG"},
    {"name": "Ukraine", "dial": "+380", "alpha2": "UA"},
    {"name": "United Arab Emirates", "dial": "+971", "alpha2": "AE"},
    {"name": "United Kingdom", "dial": "+44", "alpha2": "GB"},
    {"name": "United States", "dial": "+1", "alpha2": "US"},
    {"name": "Uruguay", "dial": "+598", "alpha2": "UY"},
    {"name": "Uzbekistan", "dial": "+998", "alpha2": "UZ"},
    {"name": "Vanuatu", "dial": "+678", "alpha2": "VU"},
    {
      "name": "Venezuela, Bolivarian Republic of Venezuela",
      "dial": "+58",
      "alpha2": "VE"
    },
    {"name": "Vietnam", "dial": "+84", "alpha2": "VN"},
    {"name": "Virgin Islands, British", "dial": "+1284", "alpha2": "VG"},
    {"name": "Virgin Islands, U.S.", "dial": "+1340", "alpha2": "VI"},
    {"name": "Wallis and Futuna", "dial": "+681", "alpha2": "WF"},
    {"name": "Yemen", "dial": "+967", "alpha2": "YE"},
    {"name": "Zambia", "dial": "+260", "alpha2": "ZM"},
    {"name": "Zimbabwe", "dial": "+263", "alpha2": "ZW"}
  ];
}
